### ISSUE TITLE
All vectors must be the same size.

### ISSUE THREAD

**Issue by irfan-zoefit** [explosion/spacy-dev-resources#20]
I've created the vectors from **spacy-dev-resource/traing** scripts. Script is old as I try to run, it throws an error.

```shell
ValueError: You must specify either total_examples or total_words, for proper alpha and progress calculations. The usual value is total_examples=model.corpus_count.
```

`model.train(corpus)` method does not work. I've changed following lines in the script and it works fine now.

```python
model.train(corpus, total_examples=model.corpus_count, epochs=model.iter)
model.wv.save_word2vec_format(out_loc, binary=False)
# both save methods works fine.
# model.save(out_loc)
```
I'm using 
* gensim==1.0.1
* spacy==1.8.2

The issue is when I try to load the vectors using `nlp.vocab.load_vectors(fname)` it throws error:

```shell
File "spacy/vocab.pyx", line 553, in spacy.vocab.Vocab.load_vectors (spacy/vocab.cpp:10950)
spacy.vocab.VectorReadError: Error reading word vectors from <_io.TextIOWrapper name=u'zoe_models/zoe-ner/vocab/vectors.txt' encoding='UTF-8'> on line 1.
All vectors must be the same size.
Prev size: 1
Curr size: 0
```

**Comment by dhernandez** [comment]
I've tried to create vectors from a small news corpus in spanish (something less than 1 000 news) fixing the lines 91 and 92 as @irfan-zoefit shows:

```python
model.train(corpus, total_examples=model.corpus_count, epochs=model.iter)
model.wv.save_word2vec_format(out_loc, binary=False)
```

If I set binary to True, when I load vectors (using `nlp.vocab.load_vectors_from_bin_loc(/path/to/file.bin)` function), it throws an IOError. In this case, output doesn't print any error description.

If I set binary to False, script generates a file that contains some errors. In my case, first line of the file contains vectors' size and total words and two lines are empty (they only contain backspaces). Trying load vector (using `nlp.vocab.load_vectors(file_buffer)` method*), fails due to theese format errors. Although, editing file and removing problematic lines Spacy loads vectors.

I supose errors in bin file are same that fails in txt file, but I don't know yet why script fails. Can you check or post your generated file, @irfan-zoefit? Have you got same errors?

*: _Careful! load_vectors() needs a buffer, not a path_
