### ISSUE TITLE
loading vocab for new language 

### ISSUE THREAD

**Issue by trungtv** [explosion/spacy-dev-resources#3]
Hi again, 
I finally managed to build new vocab for my language ( using your init.py). But, it can't work. Here is the output for spacy.load(). 

> spacy/vocab.pyx in spacy.vocab.Vocab.load (spacy/vocab.cpp:4866)()
    105         with (path / 'vocab' / 'strings.json').open('r', encoding='utf8') as file_:
    106             self.strings.load(file_)
--> 107         self.load_lexemes(path / 'vocab' / 'lexemes.bin')
    108         return self
    109 
spaCy/spacy/vocab.pyx in spacy.vocab.Vocab.load_lexemes (spacy/vocab.cpp:9365)()
    426 
    427             lexeme.vector = EMPTY_VEC
--> 428             py_str = self.strings[lexeme.orth]
    429             key = hash_string(py_str)
    430             self._by_hash.set(key, lexeme)
spaCy/spacy/strings.pyx in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2481)()
    135                     return _decode(utf8str)
    136                 else:
--> 137                     raise IndexError(string_or_id)
    138         else:
    139             if isinstance(string_or_id, bytes):
IndexError: 412564

Here showed that orth >= self.size. How is it possible?

**Comment by dvsrepo** [comment]
Hi!

Having the same issue here loading a Spanish language model created with the init.py script as well:

```Traceback (most recent call last):

  File "test_load_new_model.py", line 3, in <module>
    nlp = spacy.load("es", parser=False, tagger=False, entity=False,path="/usr/local/lib/python2.7/site-packages/spacy/data/")

  File "/usr/local/lib/python2.7/site-packages/spacy/__init__.py", line 42, in load
    return cls(**overrides)

  File "/usr/local/lib/python2.7/site-packages/spacy/language.py", line 269, in __init__
    if 'vocab' not in overrides \

  File "/usr/local/lib/python2.7/site-packages/spacy/language.py", line 56, in create_vocab
    tag_map=cls.tag_map, lemmatizer=lemmatizer)

  File "spacy/vocab.pyx", line 107, in spacy.vocab.Vocab.load (spacy/vocab.cpp:4871)

  File "spacy/vocab.pyx", line 428, in spacy.vocab.Vocab.load_lexemes (spacy/vocab.cpp:9370)

  File "spacy/strings.pyx", line 137, in spacy.strings.StringStore.__getitem__ (spacy/strings.cpp:2481)
IndexError: 416470
```

Did you manage to solve this issue?

Best wishes

**Comment by dvsrepo** [comment]
Hi again:

Just to add some more information regarding why this happens.

We managed to track it down to the way in which the StringStore is loaded/dumped.

In our case our vocabulary contained some (probably undesired symbols), which are parsed  as 0-length strings by the ujson library (which is used for loading and dumping the strings.json to build the StringStore). Using the json library this does not happen.

The issue is that those 0-length strings are skipped when creating the store, allocating memory, increasing strings.self.size, etc. In fact, there is one 0-length string which is created in the language defaults, and that one is skipped but taken into account in the class string logic (it seems that reflecting this in the size property).

Problem is, if you have more 0-length strings in your strings.json this will lead some of your strings to be out of bounds. In our case, original size of the strings list was 416471, thus logically the index should not raise and IndexError for position 416470, but our list contained two 0 sized strings thus leading the size of the StringStore object to be 416470. 

As far as I see there are two options:

1) Make sure that your corpus does not contain weird characters, that will likely influence the performance of your language models anyway.

2) We have a modification of the StringStore() class to account for this edge case (simplifying the handling of the self.size property, and allocating space even for 0-length strings. Of course it would need proper testing and a deeper understanding of the internals of the string store in spaCy, before even proposing/discussing a pull-request. We would be pleased to contribute to this great library and we can discuss this with @honnibal, but maybe is just intended to be this way.

In any case, we finally managed to properly load the Spanish lang resources into spaCy.

Best wishes,

Dani

**Comment by honnibal** [comment]
Hi Dani,

Thanks a lot for the analysis!

First of all, there are no weird characters! Every string should be valid input, and there's only one 0-length string. So if the ujson library is ignoring some inputs and instead writing the empty string, that's a serious error!

The `strings.json` is assumed to be unique --- it should be index-aligned to the vocabulary.

So it sounds like there can be one of two problems:

1. Something is seriously wrong in the internals of `ujson`, and we should switch to e.g. `cjson` or something

2. (Most likely) I'm screwing up the serialisation of unicode strings, and `ujson` is receiving malformed input.

**Comment by dvsrepo** [comment]
Hi Matt!

Thanks for your prompt response! 

You are absolutely right.

Yesterday, I have experienced a somewhat related issue with ujson, in this case during the execution of the end_training method for saving the serialization.json after training the parser with a Spanish Corpus (UD_Spanish) with the train_ud. In this case, the json.dump method with Python 2.6 exhibits a weird behaviour as well with regards to unicode and strings, so the json could not be dumped. After some research, this is a known problem with ujson for Python 2. Switching to Python 3 solved this issue and training the parser and setting up the model worked like a charm with your scripts (congrats for your great job by the way!). This led me to think that maybe if we switch to Python3 for the full lang model generation will solve this previous issue as well. 

We will during the coming days execute the full pipeline: create Spanish word vectors with 1B words corpus, generate brown clusters, word_freqs, etc. and train the parser. This time using Python 3 env. We will report on this as well. Also, we would be pleased to contribute the Spanish model, after proper testing and evaluation if you think is a good idea.

Thanks!

Dani

**Comment by honnibal** [comment]
Great!

Thanks for the pointer re ujson. That's very disappointing — I'll switch libraries.

Btw a quick pointer re Spanish: I've done some preliminary experiments on on the AnCora corpus, and in fact it's my main testbed for the spaCy 2.0 models because it's one of the few UD's that's GPL, so everyone can use it.

A little trick I found effective in my preliminary experiments: try concatenating the dependency label onto the UD POS tag, to train the tagger. The UD tags are a little bit easy on Spanish (the model is getting ~98%). Making life a little harder for the tagger so that it learns more useful features for the parser seems to help.

There's probably a clever intersection of the morphology features you could use instead, but when I tried just using all morphology features the tagset was a bit large and the model didn't do so well. Ideal would be something like CCG supertags. But for a quick and dirty hack, augmenting with the dep label was giving me about +0.5%.

**Comment by oroszgy** [comment]
Guys, I think I am facing the same issue for Hungarian. @dvsrepo do you have any hints on how did you get rid off "weird" tokens?

**Comment by dvsrepo** [comment]
Hi @oroszgy:

If I remember correctly, this issue was related to issues when using ujson using Python2. From that point on, we switched to Python3 for everything we do with spaCy. I recommend using virtualenv and Python3, although the issues might have been solved for Python2. 

Can you share your precise environment and what issues you are a facing?

We can also chat in gitter if you like.

Dani

**Comment by oroszgy** [comment]
I've just tracked down the issue, and as I see (in my case) it is rather related to `spacy`'s  `StringStore` utf8 encoding method and string handling differencies between Python version. 

More concretely, there is a strange error with surrogate strings. The code below runs well in Python2 but throws an exception in Python3.

```python
from spacy.strings import StringStore

ss = StringStore()
s = "\ud800"
ss[s]
ss.dump(open("./out", "wb"))

ss2 = StringStore()
ss2.load(open("./out", "rb"))
```

Adding this one line to my preprocessing script solves the problem:
```python
word = ftfy.fix_text(word)
```

I beleive that something similar happened with `ujson` and Python2 in your case.
